#!/usr/bin/env python

from ctypes import CDLL

CDLL("libgtk4-layer-shell.so")

import gi

gi.require_version("Gtk", "4.0")
gi.require_version("Gtk4LayerShell", "1.0")

from gi.repository import Gtk, Gdk, GLib, Pango
from gi.repository import Gtk4LayerShell as LayerShell

import argparse, sys

INTERVAL = 50

prev_pointer_position = None
inverted = None

parser = argparse.ArgumentParser(
    prog="alert",
    description="displays a fullscreen alert on every monitor",
    epilog="CSS reference: https://www.w3.org/TR/css-fonts/ --- Pango reference: https://docs.gtk.org/Pango/pango_markup.html",
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
)
parser.suggest_on_error = True
parser.add_argument(
    "text",
    type=str,
    nargs="?",
    help="text to display - unformatted or Pango markup if --pango is provided",
)
parser.add_argument(
    "-o",
    "--opacity",
    type=float,
    default="0.75",
    help="window opacity - float",
)
parser.add_argument(
    "-s",
    "--font-size",
    type=str,
    default="128px",
    help="font size - css",
)
parser.add_argument(
    "-f",
    "--font-family",
    type=str,
    default="sans-serif",
    help="font family - css",
)
parser.add_argument(
    "-i",
    "--flash-interval",
    type=int,
    default=1000,
    help="flash interval - milliseconds",
)
parser.add_argument(
    "-x",
    "--flash",
    default=True,
    action=argparse.BooleanOptionalAction,
    help="enable flashing",
)
parser.add_argument(
    "-p",
    "--pango",
    default=False,
    action=argparse.BooleanOptionalAction,
    help="enable Pango markup",
)
parser.add_argument(
    "-c",
    "--countdown",
    type=int,
    default=None,
    help="countdown, seconds - use %%c in text",
)

args = parser.parse_args()

countdown_secs = args.countdown
labels = []


def on_activate(app):
    displays = Gdk.DisplayManager.get().list_displays()
    for display in displays:
        monitors = display.get_monitors()
        n_monitors = monitors.get_n_items()
        seat = display.get_default_seat()
        pointer = seat.get_pointer()  # todo check seat != null
        for i in range(0, n_monitors):
            monitor = monitors.get_item(i)
            make_window(app, display, monitor)

    GLib.timeout_add(INTERVAL, update, app, pointer)
    if args.flash:
        GLib.timeout_add(args.flash_interval, flash, app)
    if args.countdown:
        GLib.timeout_add(1000, update_countdown)


def make_window(app, display, monitor):
    global labels

    css_str = """
        window {
          background: black;
        }
        window.inverted {
          background: white;
        }
        label {
          font-family: %s;
          font-size: %s;
          color: white;
        }
        window.inverted label {
          color: black;
        }
    """ % (
        args.font_family,
        args.font_size,
    )
    css = Gtk.CssProvider()
    css.load_from_string(css_str)
    Gtk.StyleContext.add_provider_for_display(
        display, css, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
    )

    geometry = monitor.get_geometry()
    window = Gtk.Window(application=app)
    window.set_default_size(geometry.width, geometry.height)
    window.set_resizable(False)
    window.set_opacity(args.opacity)
    window.set_title("alert")
    window.set_overflow(Gtk.Overflow.HIDDEN)

    LayerShell.init_for_window(window)
    LayerShell.set_monitor(window, monitor)
    LayerShell.set_respect_close(window, True)
    LayerShell.set_keyboard_mode(
        window, LayerShell.KeyboardMode.NONE
    )  # todo capture all kb input to close
    LayerShell.set_layer(window, LayerShell.Layer.OVERLAY)
    LayerShell.set_anchor(window, LayerShell.Edge.TOP, True)
    LayerShell.set_anchor(window, LayerShell.Edge.LEFT, True)
    LayerShell.set_anchor(window, LayerShell.Edge.RIGHT, True)

    label = Gtk.Label()
    update_label_text(label)
    labels.append(label)
    window.set_child(label)
    window.present()


def update_label_text(label):
    if args.text:
        text = format_text(args)
        label.set_wrap(True)
        label.set_justify(Gtk.Justification.CENTER)
        if args.pango:
            label.set_markup(text)
        else:
            label.set_label(text)


def update_countdown():
    global countdown_secs
    global labels

    countdown_secs -= 1
    if countdown_secs == 0:
        sys.exit(0)
    for label in labels:
        update_label_text(label)

    return True


def format_text(args):
    global countdown_secs

    if args.countdown:
        return args.text.replace("%c", pretty_time_delta(countdown_secs))
    return args.text


def pretty_time_delta(seconds):
    sign_string = "-" if seconds < 0 else ""
    seconds = abs(int(seconds))
    days, seconds = divmod(seconds, 86400)
    hours, seconds = divmod(seconds, 3600)
    minutes, seconds = divmod(seconds, 60)
    if days > 0:
        return "%s%dd %dh %dm %ds" % (sign_string, days, hours, minutes, seconds)
    elif hours > 0:
        return "%s%dh %dm %ds" % (sign_string, hours, minutes, seconds)
    elif minutes > 0:
        return "%s%dm %ds" % (sign_string, minutes, seconds)
    else:
        return "%s%ds" % (sign_string, seconds)


def flash(app):
    global inverted
    inverted = not inverted
    for window in app.get_windows():
        if inverted:
            window.add_css_class("inverted")
        else:
            window.remove_css_class("inverted")
    return True


def update(app, pointer):
    global prev_pointer_position

    _, x, y = pointer.get_surface_at_position()
    curr_pointer_position = (x, y)

    if curr_pointer_position != prev_pointer_position:
        if prev_pointer_position == None:
            prev_pointer_position = curr_pointer_position
            return True
        else:
            app.quit()
            return False

    return True


app = Gtk.Application(application_id="com.github.fr33zing.alert")
app.connect("activate", on_activate)
app.run(None)
