#!/usr/bin/env python

# Requires hwinfo

import time, traceback, io, subprocess, os.path

MODE_SWITCHER_SCRIPT_BASENAME = "mode_switcher"
MODE_SWITCHER_SCRIPT = os.path.expanduser(f"~/scripts/{MODE_SWITCHER_SCRIPT_BASENAME}")
DEFAULT_MODE = 0
MONITORS = {
    "CSOT T3 LCD Monitor": 0,
    "E241i-B1": 1,
    "WET TV": 2,
}
MODE_NAMES = {
    0: "Laptop",
    1: "Desktop",
    2: "Television",
}

script_process = None


def print_tagged(s):
    print(f"[daemon] {s}")


def main():
    prev_mode = None
    curr_mode = None

    try:
        while True:
            try:
                curr_mode = next_mode()
                if curr_mode != prev_mode:
                    prev_mode = curr_mode
                    on_mode_change(curr_mode)

                time.sleep(1)
            except Exception:
                print_tagged(traceback.format_exc())
                time.sleep(5)
    except KeyboardInterrupt:
        print_tagged("Exiting due to KeyboardInterrupt")


import subprocess


def next_mode():
    output = subprocess.check_output(["hwinfo", "--monitor", "--short"], text=True)
    monitors = output.splitlines()[1:]
    monitors = list(map(lambda m: m.lstrip(), monitors))
    return MONITORS.get(monitors[-1], DEFAULT_MODE)


def on_mode_change(mode):
    global script_process
    print_tagged(f"Switching to mode: {MODE_NAMES[mode]}")
    kill_other_script_process()
    script_process = subprocess.Popen([MODE_SWITCHER_SCRIPT, str(mode)])


def kill_other_script_process():
    global script_process
    if script_process:
        print_tagged(
            f"Killing other {MODE_SWITCHER_SCRIPT_BASENAME} script process: {script_process.pid}"
        )
        script_process.kill()
        script_process = None


if __name__ == "__main__":
    main()
