#!/usr/bin/env python

import time, sys, dbus, os, subprocess, json, pprint

FAN_CONTROL = "/proc/acpi/ibm/fan"
FAN_LEVELS = ["1", "2", "3", "4", "5", "6", "7", "full-speed"]
FAN_LEVEL_OFF = "0"
FAN_LEVEL_AUTO = "auto"


class Temperatures:
    cpu = 0
    nvme = 0
    cpu_range = (60.0, 100.0)
    nvme_range = (45.0, 74.0)

    def iter(self):
        return [("cpu", self.cpu, self.cpu_range), ("nvme", self.nvme, self.nvme_range)]


def get_temperatures():
    temps = subprocess.check_output(["sensors", "-j"], text=True)
    temps = json.loads(temps)
    out = Temperatures()
    out.cpu = float(temps["thinkpad-isa-0000"]["CPU"]["temp1_input"])
    out.nvme = float(temps["nvme-pci-0400"]["Composite"]["temp1_input"])
    return out


def fan_speed_to_level(fan_speed):
    if fan_speed == -1:
        return "level 0"
    return f"level {str(fan_speed + 1)}"


def adjust_fan_speed():
    temps = get_temperatures()
    fan_speed = -1

    for name, temp, (temp_min, temp_max) in temps.iter():
        if temp < temp_min:
            print(f"{name}: off")
            continue
        ratio = (temp - temp_min) / (temp_max - temp_min)
        i = int(round(ratio * len(FAN_LEVELS)))
        i = min(max(i, 0), len(FAN_LEVELS))
        fan_speed = max(fan_speed, i)
        print(f"{name}: {fan_speed_to_level(i)}")

    os.system(f"echo {fan_speed_to_level(fan_speed)} > {FAN_CONTROL}")


def parent_alive():
    try:
        os.kill(int(sys.argv[1]), 0)
    except ProcessLookupError:
        return False
    return True


while parent_alive():
    try:
        adjust_fan_speed()
        time.sleep(5)
    except KeyboardInterrupt:
        break


print(f"Resetting fan speed to level: {FAN_LEVEL_AUTO}")
os.system(f"echo level {FAN_LEVEL_AUTO} > {FAN_CONTROL}")
