#!/usr/bin/env python

# Requires gtk4-layer-shell
# Requires python-vlc (python-python-vlc)

from ctypes import CDLL

CDLL("libgtk4-layer-shell.so")

import gi

gi.require_version("Gtk", "4.0")
gi.require_version("Gtk4LayerShell", "1.0")

from gi.repository import Gtk, GLib
from gi.repository import Gtk4LayerShell as LayerShell

import vlc

import sys, time, os, json, subprocess, traceback, shlex, time, datetime
from urllib import request, parse
from enum import Enum
from typing import Optional, Generic, TypeVar, Callable, Any, List

SCRIPT_NAME = "qbittorrent-autopreview"
LOG_FILE = f"/tmp/{SCRIPT_NAME}.log"
DEBUG_WEBUI_CALLS = True

NAME = sys.argv[1]  # %N
SAVE_PATH = sys.argv[2]  # %D
TORRENT_ID = sys.argv[3]  # %K

API_ADDR = "127.0.0.1"
API_PORT = "8080"
API_ENDPOINT = f"http://{API_ADDR}:{API_PORT}/api/v2/torrents/"

COUNTDOWN_SECS = 30
INTERVAL = 1000
STREAMING_CONTAINER_FORMATS = [
    ".mkv",
    ".mk3d",
    ".mov",
    ".qt",
    ".asf",
    ".wmv",
    ".mxf",
    ".ts",
    ".tsv",
    ".3gp",
    ".3g2",
    ".f4v",
    ".ogv",
    ".ogx",
    ".webm",
    ".rmvb",
    ".divx",
]


class Status(Enum):
    Waiting = (False, False)
    Fatal = (False, True)
    Ready = (True, True)

    def __init__(self, should_exit, should_play):
        self.should_exit = should_exit
        self.should_play = should_play


class Error(Enum):
    NoVideosInTorrent = ("No streamable video files in torrent!", Status.Fatal)
    TooManyVideosInTorrent = ("Too many video files!", Status.Fatal)
    NoVideosInFilesystem = ("Waiting for video files...", Status.Waiting)
    TooManyVideosInFilesystem = ("Too many video files!", Status.Fatal)
    NoVideoDuration = ("Waiting to determine video duration...", Status.Waiting)
    WebUiError = ("Web UI unreachable!", Status.Fatal)
    VideoUnplayable = ("Waiting for video to become playable...", Status.Waiting)
    Buffering = ("Buffering for about %s...", Status.Waiting)
    Countdown = ("Starting in %s...", Status.Waiting)

    def __init__(self, message, status):
        self.message = message
        self.status = status


T = TypeVar("T")
Y = TypeVar("Y")


class Result(Generic[T]):
    value: Optional[T] = None
    error: Optional[Error] = None

    def __init__(self, value: Optional[T], error: Optional[Error]):
        self.value = value
        self.error = error

    def is_ok(self) -> bool:
        return bool(self.value and not self.error)

    def map(self, fn: Callable[[T], Y]) -> Result[Y]:
        if self.value:
            return Ok(fn(self.value))
        return Err(self.error)


def Ok(value):
    return Result(value, None)


def Err(error):
    return Result(None, error)


class State:
    status: Status = Status.Waiting
    error: Optional[Error] = None
    video_path: Optional[str] = None
    video_duration: Optional[int] = None
    torrent_eta: Optional[int] = None
    video_playable: bool = False
    autopreview_eta: Optional[int] = None

    countdown_start: Optional[int] = None
    countdown: bool = False

    torrent_seq_dl: Optional[bool] = None
    torrent_f_l_piece_prio: Optional[bool] = None

    def ready(self):
        self.error = None
        self.status = Status.Ready


#
# Entry point
#


def on_activate(app):
    # Main window
    window = Gtk.Window(application=app)
    window.set_default_size(100, 50)

    LayerShell.init_for_window(window)
    LayerShell.set_layer(window, LayerShell.Layer.TOP)
    LayerShell.set_anchor(window, LayerShell.Edge.TOP, True)
    LayerShell.set_margin(window, LayerShell.Edge.BOTTOM, 12)
    LayerShell.auto_exclusive_zone_enable(window)

    title = f"Downloading torrent:\n{NAME}\n"
    label = Gtk.Label(label=f"{title}\nInitializing...")
    label.set_margin_top(20)
    label.set_margin_bottom(20)
    label.set_margin_start(20)
    label.set_margin_end(20)
    window.set_child(label)
    window.present()

    state = State()

    def update_state(new_state):
        state = new_state
        lines = [title]

        if state.error:
            lines.append(state.error.message)

            if state.status == Status.Fatal:
                lines.append("\nFATAL!")
                msg = "\n".join(lines)
                notify(msg)
                nuclear_suicide()
            else:

                def add_countdown_to_last_line(countdown):
                    line = lines.pop()
                    line = line.replace("%s", pretty_time_delta(countdown))
                    lines.append(line)

                if state.error == Error.Buffering:
                    add_countdown_to_last_line(state.autopreview_eta + COUNTDOWN_SECS)
                elif state.error == Error.Countdown:
                    add_countdown_to_last_line(
                        COUNTDOWN_SECS - (time.time() - state.countdown_start)
                    )
        elif state.ready:
            lines.append("READY!")
            finish(state.video_path)

        label.set_label("\n".join(lines))

    GLib.timeout_add(INTERVAL, update, state, update_state)


def update(state, set_state):
    def _ensure_torrent_has_one_video():
        torrent_video_list = get_torrent_video_list()
        if torrent_video_list.is_ok():
            match len(torrent_video_list.value):
                case 0:
                    state.error = Error.NoVideosInTorrent
                case 1:
                    relative_path = torrent_video_list.value[0]
                    state.video_path = os.path.join(SAVE_PATH, relative_path)
                case _:
                    state.error = Error.TooManyVideosInTorrent
        else:
            state.error = torrent_video_list.error

    def _ensure_torrent_seq_dl_and_f_l_piece_prio():
        info = get_torrent_seq_dl_and_f_l_piece_prio()
        if info.is_ok():
            (seq_dl, f_l_piece_prio) = info.value
            if not seq_dl:
                result = toggle_torrent_seq_dl()
                if not result.is_ok():
                    state.error = result.error
                    return
            if not f_l_piece_prio:
                result = toggle_torrent_f_l_piece_prio()
                if not result.is_ok():
                    state.error = result.error
                    return

        else:
            state.error = info.error

    def _get_video_duration():
        if state.video_path and not state.video_duration:
            video_duration = get_video_duration(state.video_path)
            if video_duration.is_ok():
                state.video_duration = video_duration.value
            else:
                state.error = video_duration.error

    def _check_video_is_playable():
        if state.video_duration and not state.video_playable:
            if is_valid_video_file(state.video_path):
                state.video_playable = True
            else:
                state.error = Error.VideoUnplayable

    def _get_torrent_eta():
        if state.video_playable:
            torrent_eta = get_torrent_eta()
            if torrent_eta.is_ok():
                state.torrent_eta = torrent_eta.value
            else:
                state.error = torrent_eta.error

    def _calculate_autopreview_eta():
        if state.torrent_eta:
            state.autopreview_eta = state.torrent_eta - state.video_duration

            should_countdown = state.autopreview_eta <= 0

            if should_countdown != state.countdown:
                state.countdown = should_countdown
                state.countdown_start = time.time()

            if should_countdown:
                countdown_finished = (
                    time.time() - state.countdown_start > COUNTDOWN_SECS
                )
                if countdown_finished:
                    state.ready()
                else:
                    state.error = Error.Countdown
            else:
                state.error = Error.Buffering

    # Run steps in sequence
    try:
        steps = [
            _ensure_torrent_has_one_video,
            _ensure_torrent_seq_dl_and_f_l_piece_prio,
            _get_video_duration,
            _check_video_is_playable,
            _get_torrent_eta,
            _calculate_autopreview_eta,
        ]
        state.error = None
        for step in steps:
            step()
            if state.error:
                if state.error.status == Status.Fatal:
                    notify(f"FATAL ERROR:\n\n{state.error.message}")
                break
        set_state(state)
    except:
        e = traceback.format_exc()
        notify(f"EXCEPTION:\n\n{e}")
        nuclear_suicide()
    return True


def finish(path):
    os.system("~/scripts/tv_alert")
    subprocess.Popen(
        ["vlc", path],
        stdin=None,
        stdout=None,
        stderr=None,
    )
    nuclear_suicide()


#
# Utility
#


def notify(text):
    with open(LOG_FILE, "a") as file:
        file.write(text)

    body = shlex.quote(f'<b><a href="file://{LOG_FILE}">View log</a></b>\n\n{text}')
    os.system(f"notify-send -u critical '{SCRIPT_NAME}' {body}")


def api(fn, params, method="GET") -> Result[Any]:
    parts = [API_ENDPOINT, fn]
    if method == "GET":
        parts.append("?")
        for k, v in params.items():
            parts.append(f"{k}={v}")
    url = "".join(parts)

    try:

        def send_req():
            if method == "GET":
                return request.urlopen(url)
            elif method == "POST":
                body = parse.urlencode(params).encode()
                req = request.Request(url, data=body, method=method)
                return request.urlopen(req)

        with send_req() as res:
            text = res.read().decode()
            if not text and res.status == 200:
                return Ok(None)
            data = json.loads(text)
            return Ok(data)
    except Exception as e:
        if DEBUG_WEBUI_CALLS:
            raise Exception(f"Request failed ({url})") from e
        return Err(Error.WebUiError)


def get_torrent_eta() -> Result[int]:
    return api("properties", {"hash": TORRENT_ID}).map(lambda data: data["eta"])


def get_torrent_seq_dl_and_f_l_piece_prio() -> Result[tuple[bool, bool]]:
    return api("info", {"hashes": TORRENT_ID}).map(
        lambda data: (data[0]["seq_dl"], data[0]["f_l_piece_prio"])
    )


def toggle_torrent_seq_dl() -> Result[None]:
    return api("toggleSequentialDownload", {"hashes": TORRENT_ID}, "POST").map(
        lambda _: None
    )


def toggle_torrent_f_l_piece_prio() -> Result[None]:
    return api("toggleFirstLastPiecePrio", {"hashes": TORRENT_ID}, "POST").map(
        lambda _: None
    )


def get_torrent_video_list() -> Result[List[str]]:
    return api("files", {"hash": TORRENT_ID}).map(
        lambda files: list(
            map(
                lambda file: str(file["name"]),
                filter(
                    lambda file: file["priority"] != 0
                    and is_streamable_video_file(file["name"], True),
                    files,
                ),
            )
        )
    )


def get_video_duration(path) -> Result[int]:
    try:
        result = subprocess.run(
            [
                "ffprobe",
                "-v",
                "quiet",
                "-show_entries",
                "format=duration",
                "-of",
                "default=noprint_wrappers=1:nokey=1",
                path,
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        output = result.stdout.splitlines()[-1]
        duration = int(float(output))

        return Ok(duration)
    except:
        return Err(Error.NoVideoDuration)


def is_streamable_video_file(path, allow_nonexistent=False):
    if os.path.isdir(path):
        return False
    if len(path) < 5:
        return False
    path_end = path[5:]
    for ext in STREAMING_CONTAINER_FORMATS:
        if path_end.endswith(ext):
            return True
    return False


def find_all_video_paths():
    video_paths = []

    def check_files_recursive(path):
        for entry in os.listdir(path):
            full_path = os.path.join(path, entry)
            if os.path.isdir(full_path):
                check_files_recursive(full_path)
            elif is_streamable_video_file(full_path):
                video_paths.append(full_path)

    if is_streamable_video_file(SAVE_PATH):
        return [SAVE_PATH]
    elif os.path.isdir(SAVE_PATH):
        check_files_recursive(SAVE_PATH)
    return video_paths


def get_video_path() -> Result[str]:
    all_video_paths = find_all_video_paths()
    match len(all_video_paths):
        case 0:
            return Err(Error.NoVideosInFilesystem)
        case 1:
            return Ok(all_video_paths[0])
        case _:
            return Err(Error.TooManyVideosInFilesystem)


def is_valid_video_file(path):
    player = vlc.MediaPlayer(f"file://{path}")
    code = player.play()
    player.stop()
    player.release()
    return code == 0


def nuclear_suicide():
    # Nothing else works anymore...
    # Probably would need to run the vlc checking stuff in a fork
    pid = os.getpid()
    os.system(f"kill -9 {pid}")


def pretty_time_delta(seconds):
    sign_string = "-" if seconds < 0 else ""
    seconds = abs(int(seconds))
    days, seconds = divmod(seconds, 86400)
    hours, seconds = divmod(seconds, 3600)
    minutes, seconds = divmod(seconds, 60)
    if days > 0:
        return "%s%dd %dh %dm %ds" % (sign_string, days, hours, minutes, seconds)
    elif hours > 0:
        return "%s%dh %dm %ds" % (sign_string, hours, minutes, seconds)
    elif minutes > 0:
        return "%s%dm %ds" % (sign_string, minutes, seconds)
    else:
        return "%s%ds" % (sign_string, seconds)


#
# Entry point
#


def main():
    if os.path.exists(LOG_FILE):
        os.remove(LOG_FILE)

    app = Gtk.Application(application_id="com.github.fr33zing.qbittorrent_autopreview")
    app.connect("activate", on_activate)
    app.run(None)


if __name__ == "__main__":
    main()
